name: record_old
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 4.4.4
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  # record_platform_interface_old: ^0.5.0
  # record_web_old: '>=0.5.0 < 2.0.0'
  # record_windows_old: '>=0.7.1 < 2.0.0'
  # record_macos_old: '>=0.2.2 < 2.0.0'
  # record_linux_old: '>=0.4.1 < 2.0.0'

dependency_overrides:
  record_platform_interface_old:
    path: ../record_platform_interface_old
  record_web_old:
    path: ../record_web_old
  record_windows_old:
    path: ../record_windows_old
  record_macos_old:
    path: ../record_macos_old
  record_linux_old:
    path: ../record_linux_old

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
      web:
        default_package: record_web_old
      windows:
        default_package: record_windows_old
      macos:
        default_package: record_macos_old
      linux:
        default_package: record_linux_old
